# Support Vector Machines - forestfires Dataset

In [108]:
import numpy as np
import pandas as pd

from numpy import set_printoptions
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

from sklearn.model_selection import train_test_split

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix

In [109]:
fire = pd.read_csv("C:/Users/BASHAR/OneDrive/Documents/Data Science/Assignment/Assignment - 17/forestfires.csv")
fire.head()

month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  ...  monthfeb  \
0   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0  ...         0   
1   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0  ...         0   
2   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0  ...         0   
3   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2  ...         0   
4   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0  ...         0   

   monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
0         0         0         0         1         0         0         0   
1         0         0         0         0         0         0         1   
2         0         0         0         0         0         0         1   
3         0         0         0         1         0         0         0   
4         0         0         0         1         0         0         0   

   monthsep  size_category  
0         0          small  
1         0          small  
2         0          small  
3         0          small  
4         0          small  

[5 rows x 31 columns]

## EDA

In [110]:
fire.shape

(517, 31)

In [111]:
fire.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 31 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   month          517 non-null    object 
 1   day            517 non-null    object 
 2   FFMC           517 non-null    float64
 3   DMC            517 non-null    float64
 4   DC             517 non-null    float64
 5   ISI            517 non-null    float64
 6   temp           517 non-null    float64
 7   RH             517 non-null    int64  
 8   wind           517 non-null    float64
 9   rain           517 non-null    float64
 10  area           517 non-null    float64
 11  dayfri         517 non-null    int64  
 12  daymon         517 non-null    int64  
 13  daysat         517 non-null    int64  
 14  daysun         517 non-null    int64  
 15  daythu         517 non-null    int64  
 16  daytue         517 non-null    int64  
 17  daywed         517 non-null    int64  
 18  monthapr  

In [112]:
fire.isna().sum()

month            0
day              0
FFMC             0
DMC              0
DC               0
ISI              0
temp             0
RH               0
wind             0
rain             0
area             0
dayfri           0
daymon           0
daysat           0
daysun           0
daythu           0
daytue           0
daywed           0
monthapr         0
monthaug         0
monthdec         0
monthfeb         0
monthjan         0
monthjul         0
monthjun         0
monthmar         0
monthmay         0
monthnov         0
monthoct         0
monthsep         0
size_category    0
dtype: int64

In [113]:
fire[fire.duplicated()].shape

(8, 31)

In [114]:
fire[fire.duplicated()]

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  ...  monthfeb  \
53    aug  wed  92.1  111.2  654.1   9.6  20.4  42   4.9   0.0  ...         0   
100   aug  sun  91.4  142.4  601.4  10.6  19.8  39   5.4   0.0  ...         0   
215   mar  sat  91.7   35.8   80.8   7.8  17.0  27   4.9   0.0  ...         0   
303   jun  fri  91.1   94.1  232.1   7.1  19.2  38   4.5   0.0  ...         0   
426   aug  thu  91.6  248.4  753.8   6.3  20.4  56   2.2   0.0  ...         0   
461   aug  sat  93.7  231.1  715.1   8.4  18.9  64   4.9   0.0  ...         0   
501   aug  tue  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8  ...         0   
508   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0  ...         0   

     monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
53          0         0         0         0         0         0         0   
100         0         0         0         0         0         0         0   
215         0         0         0         1         0         0         0   
303         0         0         1         0         0         0         0   
426         0         0         0         0         0         0         0   
461         0         0         0         0         0         0         0   
501         0         0         0         0         0         0         0   
508         0         0         0         0         0         0         0   

     monthsep  size_category  
53          0          small  
100         0          small  
215         0          large  
303         0          small  
426         0          small  
461         0          small  
501         0          small  
508         0          small  

[8 rows x 31 columns]

In [115]:
fire1 = fire.drop_duplicates()
fire1.iloc[50:55]

month  day  FFMC    DMC     DC  ISI  temp  RH  wind  rain  ...  monthfeb  \
50   sep  thu  92.9  137.0  706.4  9.2  20.8  17   1.3   0.0  ...         0   
51   aug  sun  90.2   99.6  631.2  6.3  21.5  34   2.2   0.0  ...         0   
52   aug  wed  92.1  111.2  654.1  9.6  20.4  42   4.9   0.0  ...         0   
54   aug  thu  91.7  114.3  661.3  6.3  17.6  45   3.6   0.0  ...         0   
55   sep  thu  92.9  137.0  706.4  9.2  27.7  24   2.2   0.0  ...         0   

    monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
50         0         0         0         0         0         0         0   
51         0         0         0         0         0         0         0   
52         0         0         0         0         0         0         0   
54         0         0         0         0         0         0         0   
55         0         0         0         0         0         0         0   

    monthsep  size_category  
50         1          small  
51         0          small  
52         0          small  
54         0          small  
55         1          small  

[5 rows x 31 columns]

In [116]:
fire1.shape

(509, 31)

In [117]:
fire2 = fire1.reset_index()
fire2 = fire2.drop(columns="index")
fire2.iloc[50:55]

month  day  FFMC    DMC     DC  ISI  temp  RH  wind  rain  ...  monthfeb  \
50   sep  thu  92.9  137.0  706.4  9.2  20.8  17   1.3   0.0  ...         0   
51   aug  sun  90.2   99.6  631.2  6.3  21.5  34   2.2   0.0  ...         0   
52   aug  wed  92.1  111.2  654.1  9.6  20.4  42   4.9   0.0  ...         0   
53   aug  thu  91.7  114.3  661.3  6.3  17.6  45   3.6   0.0  ...         0   
54   sep  thu  92.9  137.0  706.4  9.2  27.7  24   2.2   0.0  ...         0   

    monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
50         0         0         0         0         0         0         0   
51         0         0         0         0         0         0         0   
52         0         0         0         0         0         0         0   
53         0         0         0         0         0         0         0   
54         0         0         0         0         0         0         0   

    monthsep  size_category  
50         1          small  
51         0          small  
52         0          small  
53         0          small  
54         1          small  

[5 rows x 31 columns]

In [118]:
fire3 = pd.get_dummies(fire2, columns=["size_category"], drop_first=True)
fire3

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  ...  monthfeb  \
0     mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0  ...         0   
1     oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0  ...         0   
2     oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0  ...         0   
3     mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2  ...         0   
4     mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0  ...         0   
..    ...  ...   ...    ...    ...   ...   ...  ..   ...   ...  ...       ...   
504   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0  ...         0   
505   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  ...         0   
506   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  ...         0   
507   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0  ...         0   
508   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0  ...         0   

     monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
0           0         0         0         1         0         0         0   
1           0         0         0         0         0         0         1   
2           0         0         0         0         0         0         1   
3           0         0         0         1         0         0         0   
4           0         0         0         1         0         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
504         0         0         0         0         0         0         0   
505         0         0         0         0         0         0         0   
506         0         0         0         0         0         0         0   
507         0         0         0         0         0         0         0   
508         0         0         0         0         0         1         0   

     monthsep  size_category_small  
0           0                    1  
1           0                    1  
2           0                    1  
3           0                    1  
4           0                    1  
..        ...                  ...  
504         0                    0  
505         0                    0  
506         0                    0  
507         0                    1  
508         0                    1  

[509 rows x 31 columns]

In [119]:
fire4 = fire3.iloc[:,2:31]
fire4.head()

FFMC   DMC     DC  ISI  temp  RH  wind  rain  area  dayfri  ...  monthfeb  \
0  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0       1  ...         0   
1  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0       0  ...         0   
2  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0       0  ...         0   
3  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0       1  ...         0   
4  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0       0  ...         0   

   monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
0         0         0         0         1         0         0         0   
1         0         0         0         0         0         0         1   
2         0         0         0         0         0         0         1   
3         0         0         0         1         0         0         0   
4         0         0         0         1         0         0         0   

   monthsep  size_category_small  
0         0                    1  
1         0                    1  
2         0                    1  
3         0                    1  
4         0                    1  

[5 rows x 29 columns]

In [120]:
fire4.shape

(509, 29)

## Standardization

In [121]:
std = fire4.values
scaler = StandardScaler().fit(std)
rescaledX = scaler.transform(std)

set_printoptions(precision=2)
print(rescaledX[0:5,:])

[[-7.96e-01 -1.32e+00 -1.83e+00 -8.57e-01 -1.83e+00  4.13e-01  1.49e+00
  -6.90e-02 -2.03e-01  2.27e+00 -4.12e-01 -4.38e-01 -4.76e-01 -3.66e-01
  -3.76e-01 -3.41e-01 -1.34e-01 -7.33e-01 -1.34e-01 -2.02e-01 -6.28e-02
  -2.59e-01 -1.80e-01  2.93e+00 -6.28e-02 -4.44e-02 -1.74e-01 -7.14e-01
   6.10e-01]
 [-3.26e-03 -1.17e+00  4.89e-01 -5.07e-01 -1.48e-01 -6.88e-01 -1.73e+00
  -6.90e-02 -2.03e-01 -4.41e-01 -4.12e-01 -4.38e-01 -4.76e-01 -3.66e-01
   2.66e+00 -3.41e-01 -1.34e-01 -7.33e-01 -1.34e-01 -2.02e-01 -6.28e-02
  -2.59e-01 -1.80e-01 -3.41e-01 -6.28e-02 -4.44e-02  5.74e+00 -7.14e-01
   6.10e-01]
 [-3.26e-03 -1.04e+00  5.61e-01 -5.07e-01 -7.31e-01 -6.88e-01 -1.51e+00
  -6.90e-02 -2.03e-01 -4.41e-01 -4.12e-01  2.28e+00 -4.76e-01 -3.66e-01
  -3.76e-01 -3.41e-01 -1.34e-01 -7.33e-01 -1.34e-01 -2.02e-01 -6.28e-02
  -2.59e-01 -1.80e-01 -3.41e-01 -6.28e-02 -4.44e-02  5.74e+00 -7.14e-01
   6.10e-01]
 [ 1.95e-01 -1.21e+00 -1.90e+00 -5.15e-03 -1.81e+00  3.23e+00 -6.33e-03
   6.07e-01 -2.03e-01  2.

In [122]:
X = std[:, 0:28]
Y = std[:, 28]

## Recursive Feature Elimination

In [123]:
model = LogisticRegression()
rfe = RFE(model, 10)
fit = rfe.fit(X, Y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass n_features_to_select=10 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

I

In [124]:
fit.n_features_

10

In [125]:
fit.support_

array([False, False, False, False, False, False, False, False,  True,
       False, False,  True,  True,  True,  True, False, False,  True,
        True, False, False,  True, False, False, False, False,  True,
        True])

In [126]:
fire5 = fire4.iloc[:,[4, 6, 9, 11, 12, 15, 17, 20, 21, 26, 28]]
fire5.head()

temp  wind  dayfri  daysat  daysun  daywed  monthaug  monthjan  monthjul  \
0   8.2   6.7       1       0       0       0         0         0         0   
1  18.0   0.9       0       0       0       0         0         0         0   
2  14.6   1.3       0       1       0       0         0         0         0   
3   8.3   4.0       1       0       0       0         0         0         0   
4  11.4   1.8       0       0       1       0         0         0         0   

   monthoct  size_category_small  
0         0                    1  
1         1                    1  
2         1                    1  
3         0                    1  
4         0                    1

In [127]:
array = fire5.values
array

array([[ 8.2,  6.7,  1. , ...,  0. ,  0. ,  1. ],
       [18. ,  0.9,  0. , ...,  0. ,  1. ,  1. ],
       [14.6,  1.3,  0. , ...,  0. ,  1. ,  1. ],
       ...,
       [21.2,  6.7,  0. , ...,  0. ,  0. ,  0. ],
       [25.6,  4. ,  0. , ...,  0. ,  0. ,  1. ],
       [11.8,  4.5,  0. , ...,  0. ,  0. ,  1. ]])

## Train & Test Split

In [128]:
x = array[:, 0:10]
y = array[:, 10]

In [129]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, shuffle=True)

## Building model using Support Vector Machines

In [130]:
model = SVC(kernel='rbf', random_state=7, gamma=50, C=5)
model.fit(x_train, y_train)

SVC(C=5, gamma=50, random_state=7)

In [131]:
pred = model.predict(x_test)
pred

array([0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.])

In [132]:
confusion_matrix(y_test, pred)

array([[  3,  32],
       [  6, 112]], dtype=int64)

In [133]:
accuracy = accuracy_score(y_test, pred)
print((accuracy)*100)

75.16339869281046


In [134]:
print("The accuracy of the svm classifier on training data is {:.2f} out of 1".format(model.score(x_train, y_train)*100))

print("The accuracy of the svm classifier on test data is {:.2f} out of 1".format(model.score(x_test, y_test)*100))

The accuracy of the svm classifier on training data is 97.75 out of 1
The accuracy of the svm classifier on test data is 75.16 out of 1
